name: OpenBoard
version: 0.1.4
author: Arraying
main: de.arraying.openboard.OpenBoard
softdepend: [PlaceholderAPI]
website: 'https://github.com/Arraying/OpenBoard'
commands:
  obreload:
    aliases: [obr, openboardreload]
    description: Reloads OpenBoard scoreboards and nametags.
    usage: /obreload